import { builder } from "@builder.io/react";

import "./components/Box/cmp.builder";
import "./components/Container/cmp.builder";
import "./components/Section/cmp.builder";
import "./components/Column/cmp.builder";
import "./components/Row/cmp.builder";
import "./components/Button/cmp.builder";
import "./components/Text/cmp.builder";
import "./components/TextGradient/cmp.builder";
import "./components/H1/cmp.builder";
import "./components/H2/cmp.builder";
import "./components/BulletList/cmp.builder";
import "./components/Header/cmp.builder";
import "./components/Footer/cmp.builder";
import "./components/ContactForm/cmp.builder";
import "./components/SignMeUpForm/cmp.builder";
import "./components/Breadcrumb/cmp.builder";
import "./components/Image/cmp.builder";
import "./components/Column/cmp.builder";
import "./components/CardWithSideImage/cmp.builder";
import "./components/ObjectImage/cmp.builder";
import "./components/ThemeBox/cmp.builder";
import "./components/Tag/cmp.builder";
import "./components/BlockTag/cmp.builder";
import "./components/Icon/cmp.builder";
import "./components/Blog/BlogCategories/cmp.builder";
import "./components/Blog/BlogTags/cmp.builder";
import "./components/hiddenFromEditor.builder";

builder.init(process.env.NEXT_PUBLIC_BUILDER_API_KEY!);
