name: Push on IPFS

on:
  push:
    branches:
      - release/**
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - site: "twentysix-website"
            key: "fd4e1a4bdbc240f0b17c0e77aee16d01"
            siteHomeUrl: "https://twentysix.cloud/"
          - site: "aleph-website"
            key: "5729da240c404db0a5adeed7b8d8ae9f"
            siteHomeUrl: "https://aleph.im/"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          NEXT_PUBLIC_BUILDER_API_KEY: ${{ matrix.key }}
          SITE_HOME_URL: ${{ matrix.siteHomeUrl }}
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" FONTAWESOME_NPM_AUTH_TOKEN
          npm ci
          npm run build
          touch out/.nojekyll

      - uses: actions/upload-artifact@v3
        with:
          name: front-cms-${{ matrix.key }}
          path: out/

      - uses: actions/download-artifact@v3
        with:
          name: front-cms-${{ matrix.key }}
          path: out/

      - name: Push on IPFS
        run: |
          find .
          pip install 'aioipfs>=0.6.2'
          python3 ./scripts/push_on_ipfs.py
          export IPFS_CID=$(python3 ./scripts/push_on_ipfs.py)
          echo $IPFS_CID
          echo "CID: $IPFS_CID" >> $GITHUB_STEP_SUMMARY
